Fix/fake parents
cytoscape/cytoscape.js-compound-drag-and-drop pull request #22
Opened 2021-11-21 23:23 UTC by sashokbg

I have opened this PR in place of #17.

As you have suggested the library now detects automatically if a parent node is a "real node" and it prevents its deletion.
To make this work I have added a class called "cdnd-fake-parent" for parents that can be removed.

I have also added E2E tests that prove it works.

You can run them with **npm run test:e2e** and check the generated report in **test/reports**

2021-12-06 16:58 UTC, maxkfranz commented
I've reviewed the PR, and it looks great.

Before it's merged in, do you think it would make sense to use a class name like `cdnd-new-parent` to be consistent with the naming of `newParentNode()` in `options`?

https://github.com/cytoscape/cytoscape.js-compound-drag-and-drop#api

2022-01-12 10:14 UTC, sashokbg commented
Hello @maxkfranz I have updated the code to change the class to cdnd-new-parent and also rebased the branch with master.

2022-01-13 17:39 UTC, maxkfranz requested changes
Looks good.  I think the readme documentation just needs a few tweaks, and then the PR can be merged in.

Is everything new from this PR documented in the readme?  I don't see any additions for the new class name, for example.

2022-01-13 17:39 UTC, maxkfranz commented on README.md
> +  newParentNode: (grabbedNode, dropSibling) => ({}), // specifies element json for parent nodes added by dropping an orphan node on another orphan (a drop sibling). You can chose to return the dropSi
It looks like this got moved in the merge.  It should be beside the other functions, like dropSibling

2022-02-24 09:06 UTC, sashokbg commented
Hello, I have documented the new class and also moved the callback description up. Sorry for the delay

2022-02-24 09:19 UTC, philwronski approved these changes

2022-02-28 15:00 UTC, maxkfranz approved these changes

2022-02-28 15:00 UTC, merged

2022-03-03 16:12 UTC, maxkfranz commented
v1.1.0 released